# Generated by Django 3.1.5 on 2021-02-20 00:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_auto_20210219_1953'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='closed',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='winners', to=settings.AUTH_USER_MODEL),
        ),
    ]
